import streamlit as st
from PIL import Image
import tempfile

from src.predict import predict_image
from src.ai_helper import get_disease_information

# ==========================================
# PAGE CONFIGURATION
# ==========================================

st.set_page_config(
    page_title="AI Skin Cancer Detection",
    page_icon="🩺",
    layout="wide"
)

# ==========================================
# HEADER
# ==========================================

st.title("🩺 AI Skin Cancer Detection System")

st.markdown("""
This application uses a **Deep Learning (TensorFlow)** model to predict
the most likely skin disease from an uploaded image.

After prediction, **Groq AI (Llama 3.3)** generates an educational report.

> **⚠️ Note:** This application is for educational purposes only and is **not** a medical diagnosis.
""")

# ==========================================
# SIDEBAR
# ==========================================

with st.sidebar:

    st.header("About")

    st.write("""
### Technologies Used

- TensorFlow
- EfficientNetB0
- HAM10000 Dataset
- Groq AI (Llama 3.3)
- Streamlit
""")

    st.info(
        "Educational Use Only\n\n"
        "Always consult a dermatologist for medical advice."
    )

# ==========================================
# IMAGE UPLOAD
# ==========================================

uploaded_file = st.file_uploader(
    "📤 Upload Skin Image",
    type=["jpg", "jpeg", "png"]
)

# ==========================================
# PREDICTION
# ==========================================

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns([1, 1])

    with col1:

        st.image(
            image,
            caption="Uploaded Image",
            use_container_width=True
        )

    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as temp_file:

        image.save(temp_file.name)

        disease, confidence = predict_image(temp_file.name)

    confidence_percent = confidence * 100

    with col2:

        st.success("## 🩺 Prediction")

        st.markdown(f"# **{disease}**")

        st.metric(
            label="Confidence",
            value=f"{confidence_percent:.2f}%"
        )

        st.progress(float(confidence))

        if confidence_percent >= 80:
            st.success("🟢 High Confidence Prediction")

        elif confidence_percent >= 60:
            st.warning("🟡 Moderate Confidence Prediction")

        else:
            st.error("🔴 Low Confidence Prediction")

    # ==========================================
    # CONFIDENCE INTERPRETATION
    # ==========================================

    st.divider()

    st.subheader("📊 Confidence Interpretation")

    if confidence_percent >= 80:

        st.info(
            "The AI model has high confidence in this prediction. "
            "However, this is **not** a confirmed medical diagnosis."
        )

    elif confidence_percent >= 60:

        st.warning(
            "The prediction has moderate confidence. "
            "Please interpret the result carefully."
        )

    else:

        st.error(
            "The prediction has low confidence. "
            "The uploaded image may not closely match the trained disease categories."
        )

    # ==========================================
    # AI REPORT
    # ==========================================

    st.divider()

    st.header("🤖 AI Medical Report")

    with st.spinner("Generating report using Groq AI..."):

        try:

            report = get_disease_information(
                disease,
                confidence_percent
            )

            st.markdown(report)

            st.download_button(
                label="📥 Download AI Report",
                data=report,
                file_name=f"{disease}_AI_Report.txt",
                mime="text/plain"
            )

        except Exception as e:

            st.error("Unable to generate AI report.")

            st.code(str(e))

# ==========================================
# FOOTER
# ==========================================

st.divider()

st.warning("""
## ⚠️ Medical Disclaimer

This application is intended **only for educational and research purposes**.

- The prediction generated by the AI model is **not a confirmed medical diagnosis**.
- The information generated by **Groq AI (Llama 3.3)** is for educational purposes only.
- Do **not** use this application as a substitute for professional medical advice.
- If you notice a suspicious skin lesion, rapid changes in size, color, shape, bleeding, pain, or any concerning symptoms, consult a qualified dermatologist promptly.
""")